### PR TITLE
bump ktor client version to 2.2.4, kotlin -- 1.6.10

### PR DESCRIPTION
**Pull request by KazankovMarch**
there are some vulnerabilities in current 1.6.4 version https://security.snyk.io/package/maven/io.ktor:ktor-client-core/1.6.4

these are the latest versions of kotlin and ktor the project builds with. There are some changes with JS in kotlin multiplatform 1.6.10 causes wasm error; there are incompatible versions of libs in ktor 2.3.0

### CODE REVIEW

**Comment by KazankovMarch** [comment]
it should fix issue https://github.com/BoD/klibnotion/issues/36

**Review by BoD — APPROVED** [review]

**Comment by BoD** [comment]
Thanks a lot for this!

**Comment by BoD** [comment]
Actually, while we're at it, could we use Ktor 2.3.4 and Kotlin 1.9.10?

**Comment by BoD** [comment]
I did that in #42

**Pull request merged**
